config/routes.rb
Rails.application.routes.draw do
  resources:route
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/route.rb
class Route < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/route_controller.rb
class RouteController < ApplicationController
  def index
    @route=Route.all
    
  end

  def new
    @route=Route.new
  end

  def create
    if request.post?
     @route=Route.create(route_params)
    end
    redirect_to @route
    
  end

  def show
    @route=Route.find(params[:id])
 gon.depature_place=@route['depature_place']
 gon.destination_place=@route['destination_place']
 gon.transition_method=@route['transition_method']
 

  end

  def destroy
    route=Route.find(params[:id])
    route.destroy
    redirect_to '/route'
  end

  private 
def route_params
 params.require(:route).permit(:id,:depature_place,:destination_place,:transition_method)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/route_helper.rb
module RouteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Googleroute</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
  </head>

  <body>
    <%= yield %>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDJzux1JhQNtBO-9TNu2fNp2hzzJOcyln8&libraries=places"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  </body>
</html>

app/views/route/index.html.erb
<table>
    <tr>
    <th>インデックス番号</th><th>出発場所</th><th>目的地</th><th>移動方法</th>
    
    </tr>
    <%@route.each do |route|%>
    <tr>
        <td><%=route.id%></td>
        <td><%=route.depature_place%></td>
        <td><%=route.destination_place%></td>
        <td><%=route.transition_method%></td>
        <td><%=link_to 'show', route_path(route)%></td>
        <td><%= link_to 'Destroy' , route_path(route.id) , method: :delete,data: {confirm: 'Are you sure?' } %></td>
    </tr>
    <%end%>
</table>

<%= link_to 'プランを作る', 'route/new'%>

app/views/route/new.html.erb
<%= form_for(@route, url:{controller:'route',action:'create'}) do |form|%>
    <div>
    <label for='depature_place'>出発地</label>
    <%=form.text_field:depature_place%>

    </div>
    <label for='destination_place'>目的地</label>
    <%=form.text_field:destination_place%>

    <div>
    <label for='transition_method'>移動方法</label>
    <%=form.select:transition_method,[["車","DRIVING"],["徒歩","WALKING"]]%>

    </div>

<%=form.submit%>

<%end%>

<%= link_to '一覧に戻る', '/route'%>

app/views/route/show.html.erb
<div>

★結果★<br />
<div id="results" style="width: 100%; height: 200px; border: 1px dotted; padding: 10px; overflow-y: scroll;"></div>
</div>

<%= link_to '一覧に戻る', '/route'%>

<script type="text/javascript">

window.onload=function getRoute(){




var directionsService = new google.maps.DirectionsService();

directionsService.route({
    origin:gon.depature_place,
    destination:gon.destination_place,
    travelMode:gon.transition_method
}, displayResults
);

}


function displayResults(response,status){
console.log(response.routes[0].legs[0].distance.text);
console.log(response.routes[0].legs[0].duration.text);


if(status == google.maps.places.PlacesServiceStatus.OK){
const duration = response.routes[0].legs[0].duration.text;
const distance  = response.routes[0].legs[0].distance.text;

let words = '【出発地】'+gon.depature_place+'\n'+'【目的地】'+gon.destination_place+'\n'+'【所要時間】' + duration + '\n' +
             '【移動距離】　' + distance + '\n';

document.getElementById("results").innerHTML =words

}

}

</script>